#importing all the neccessary dependencies and libraries
from .queries import *

run_query(query1)
run_query(query2)
run_query(query3)
run_query(query4)
run_query(query5)
run_query(query6)
run_query(query7)
run_query(query8)
run_query(query9)
run_query(query10)
run_query(query11)
run_query(query12)
run_query(query13)
run_query(query14)
run_query(query15)
run_query(query16)
run_query(query17)
run_query(query18)
run_query(query19)
run_query(query20)
run_query(query_not_working)
